### PR TITLE
Use conda packages to build the page

### PR DESCRIPTION
**Pull request by ocefpaf**
I updated `Travis-CI` to reflect the same env I have locally. Maybe that will fix the page build.

### CODE REVIEW

**Comment by ocefpaf** [comment]
And we are back in business! :tada: 

https://sea-mat.github.io/sea-mat/ 

Thanks @asmeurer again for the assist!

**Comment by asmeurer** [comment]
I did not know about `language: generic`. I've tried [removing the language](https://github.com/drdoctr/doctr/pull/94) but then it defaults to Ruby, which is slightly slower than Python. `language: generic` appears to not do either, which should be faster.

**Comment by ocefpaf** [comment]
I never timed it but we chose `language: generic`  for `conda-forge` some time ago and I just kept using it for conda-related projects.

**Comment by asmeurer** [comment]
It actually seems to be [about the same](https://github.com/drdoctr/doctr/pull/152).

**Comment by rsignell-usgs** [comment]
So just to make sure I've got this right:
* In the [first line of Travis.yml](https://github.com/sea-mat/sea-mat/blob/master/.travis.yml#L1) we used to have `language: python` but then changes were not detected by `doctr`. 
* Since we are actually not using Travis Python (using Python via miniconda instead), we tried switching to`language: null` but that turns out to specify Ruby. 
* The solution is to use `language: generic` for Miniconda-based workflows

**Comment by ocefpaf** [comment]
> * In the first line of Travis.yml https://github.com/sea-mat/sea-mat/blob/master/.travis.yml#L1, we used to have `language: python` but then changes were not detected by `doctr`. 

The language there has no relation with the `doctr` issue before. I just changed that because we don't need Travis-CI python when using `miniconda`. 


> * Since we are actually not using Travis Python (using Python via miniconda instead), we tried switching to`language: null` but that turns out to specify Ruby. 

The `null`, `Python` or `Ruby` have no bearing here. I just like to use `generic` to be clear we are not relying on anything from Travis-CI.


> * The solution is to use `language: generic` for Miniconda-based workflows

Not really a solution, just a preference.

The real issue was that we did not clean the `gh-pages` before using `doctr`. After I cleaned that we had an issue with the versions of `mkdcos` (not `doctr`). So I switched us to the `conda` version of those packages and everything worked.

**Pull request merged**
