### PR TITLE
Key for doctr deployment.

### PR DESCRIPTION
**Pull request by ocefpaf**
Using `doctr configure --no-upload-key` worked for me. See https://github.com/drdoctr/doctr/issues/148#issuecomment-270796137

The difference is that we need to add the key manually but I already did that.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Now I am sure I am doing something wrong... The last time I used `doctr configure` I remember using `myrepo/myrepo` for both build, and deploy and `Travis-CI` passed on the forked branch too.

@asmeurer can you spot anything obvious I am doing wrong?

**Comment by rsignell-usgs** [comment]
I tried and failed also: https://github.com/sea-mat/sea-mat/pull/6

**Comment by asmeurer** [comment]
I'm unsure. 128 is an odd exit code. @gforsyth any ideas?

**Comment by asmeurer** [comment]
Oh I didn't see the error:

```
git push -u doctr_remote gh-pages
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/sea-mat/sea-mat.git/'
```

BUT, doctr shouldn't even be attempting to push, since this is a pull request! What is going on here?

**Comment by asmeurer** [comment]
Oh I see the bug. It isn't checking if it can push before trying to create the gh-pages branch. See https://github.com/drdoctr/doctr/issues/145. 

For now, the workaround is to create an empty `gh-pages` branch on this repo. Once it exists this problem with go away:

```
git checkout --orphan gh-pages
touch .nojekyll
git add .nojekyll
git commit -m "Create gh-pages branch with .nojekyll"
git push origin gh-pages
git checkout -
```

**Comment by ocefpaf** [comment]
@rsignell-usgs did you performed the instruction in https://github.com/sea-mat/sea-mat/pull/5#issuecomment-270996676 ?

**Comment by ocefpaf** [comment]
Thanks for looking into @asmeurer!

**Pull request closed without merging**
